### ISSUE TITLE
Add LICENSE.md da FSF GNU GPL v3

### ISSUE THREAD

**Issue by terremoth** [cosmicpb/FascistFree#2]
Se este é um free software, e "free assange" é uma bandeira a levantar então nada mais justo que adicionar uma licença pro repo (LICENSE.md) da GPL v3

LGTM? Se quiser eu faça o PR com ela.

**Comment by cosmicpb** [comment]
Seria top! Se puder fazer, por favor. Adiciono os créditos para ti.

Obrigado pela ajuda.

**Comment by terremoth** [comment]
Adiciono sim, mas nem quero créditos não, só quero +1 repo GPLv3

**Comment by terremoth** [comment]
@cosmicpb 
PR:
https://github.com/cosmicpb/FascistFree/pull/4

**Comment by cosmicpb** [comment]
Pronto!
Valeu meu querido!
Obrigado pela ajuda, assim se faz a democracia!
