### ISSUE TITLE
Hardcoded windows diretório 

### ISSUE THREAD

**Issue by terremoth** [cosmicpb/FascistFree#3]
Isso aqui assim em string hardcoded direto no código não é um problema já que o diretorio de cada um varia de nome?
"paulo.baldacim"

e pra quem tá no linux?

![image](https://user-images.githubusercontent.com/11032344/211421029-a85807ba-0390-4013-b7b5-1e25ee6f07d8.png)

**Comment by cosmicpb** [comment]
Você tem plena razão, deixei isso passar em branco.

Obrigado pelo report.

**Comment by cosmicpb** [comment]
Resolvido.
