### ISSUE TITLE
Tentei com o carinha que quebrou o relógio e não detectou

### ISSUE THREAD

**Issue by leo-smi** [cosmicpb/FascistFree#8]
Usei 5 frames por segundo, chequei os frames e o rosto frontal dele estava lá. Será que a detecção está com algum viés? Teria como diminuir o fator de detecção (detection rate) pra um valor menor, tipo uns 50% de certeza. Tentei procurar na documentação mas não achei. Eu testei com um patriotário branco na janela de um ônibus e funcionou.

![580](https://user-images.githubusercontent.com/20663547/214312109-d697da8d-7f03-40fb-bf76-17a8e747ab85.jpg)
![585](https://user-images.githubusercontent.com/20663547/214312195-7d729461-37a6-46da-b2bd-4461437cf86d.jpg)

**Comment by cosmicpb** [comment]
Isso pode acontecer, sim. Utilizamos um pacote de dados e treinamento pré-definidos pelo opencv.

Acredito que o principal seja pela qualidade da imagem após o corte dos frames, que cai bastante (vale melhorar esse ponto) e provavelmente não permite uma detecção limpa.

Obrigado pelo feedback
